In [2]:
#Write a NumPy program to test whether none of the elements of a given array is zero.#

In [3]:
import numpy as np

In [4]:
def zero_count(arr):
    arr=np.array(arr)
    count = np.count_nonzero(arr)
    return True if (arr.size-count)>0 else False

In [5]:
zero_count([[1,2,3],[4,5,6],[7,8,9]])

False

In [6]:
#Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [7]:
def nonzero_count(arr):
    arr=np.array(arr)
    count = np.count_nonzero(arr)
    return True if count>0 else False

In [8]:
nonzero_count([[0,0,0],[0,0,0],[0,0,0]])

False

In [9]:
#Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given

In [10]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,9],[7,8,9]])
assert arr1.shape == arr2.shape, 'Matrices should have same size'
m,n = arr1.shape
count = 0
for i in range (m):
    for j in range (n):
        if arr1[i][j] == arr2[i][j]:
            count+=1
if count == arr1.size:
    print('Matrices are equal element wise')
else:
    print('Matrices are not equal element wise')
        


Matrices are not equal element wise


In [11]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [12]:
a= np.zeros([10,1])

In [13]:
b= np.ones([10,1])

In [14]:
c=b*5

In [15]:
d=np.vstack((a,b,c))

In [16]:
print(d)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]
 [5.]]


In [17]:
#Write a NumPy program to create an array of the integers from 30 to 70.

In [18]:
arr= np.arange(30,70)

In [19]:
#Write a NumPy program to create a 3x3 identity matrix

In [20]:
eye=np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#Write a NumPy program to generate a random number between 0 and 1

In [22]:
rand=np.random.rand(1)
print(rand)

[0.06562851]


In [23]:
#Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [24]:
rand=np.random.rand(15,1)
print(rand)

[[0.94850993]
 [0.169244  ]
 [0.10801009]
 [0.701349  ]
 [0.2454789 ]
 [0.2162114 ]
 [0.45224383]
 [0.87788805]
 [0.62469222]
 [0.69964932]
 [0.65063636]
 [0.84087273]
 [0.68382747]
 [0.4058886 ]
 [0.56109483]]


In [25]:
#Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [29]:
arr= np.arange(15,56)

In [34]:
for i in range(arr[1],arr[-1]):
    print(i)

16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54


In [35]:
#Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [39]:
x = np.random.randint(0,11,5)
print(x)

[9 5 6 7 6]


In [ ]:
#Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [50]:
a=np.zeros([10,10])

In [51]:
a[0]=1

In [52]:
a[9]=1

In [54]:
a[:,0]=1

In [56]:
a[:,9]=1

In [57]:
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [58]:
#Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [73]:

M=np.diag([1,2,3,4,5])

In [74]:
print(M)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
